name: tetmesht
channels:
  - defaults
  - conda-forge
dependencies:
  - pip<24.0
  - vtk
  - numpy<1.23.0
  - scipy
  - mrcfile
  - doxygen
  - pylint
  - python
  - pyopengl
  - pyqt
  - pyrr
  - biopython
